[vms]
consul1 ansible_host=159.223.239.63
consul2 ansible_host=152.42.138.130
consul3 ansible_host=152.42.132.24
haproxy ansible_host=146.190.16.205
pg-master ansible_host=68.183.13.138
pg-replica ansible_host=146.190.29.105

[pg_master]
pg-master ansible_host=68.183.13.138

[pg_replica]
pg-replica ansible_host=146.190.29.105

[consul]
consul1 ansible_host=159.223.239.63
consul2 ansible_host=152.42.138.130
consul3 ansible_host=152.42.132.24

[haproxy_hosts]
haproxy ansible_host=146.190.16.205

[all:vars]
ansible_user=root
ansible_password={{ root_password }}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
